---
- name: configuration
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true
  tasks:
  - name: enable repos
    template:
      src: open_three-tier-app.repo
      dest: /etc/yum.repos.d/open_three-tier-app.repo
      mode: 0644

- name: deploy haproxy
  hosts: frontends
  gather_facts: false # remove later! speeds up testing
  become: true
  tags:
    - haproxy
  roles:
    - haproxy