---
- name: configuration
  hosts: all
  gather_facts: false 
  become: true
  tags:
    - config_repos
  tasks:
  - name: enable repos
    template:
      src: open_three-tier-app.repo
      dest: /etc/yum.repos.d/open_three-tier-app.repo
      mode: 0644

- name: deploy haproxy
  hosts: frontends
  gather_facts: false 
  tags:
    - haproxy
  roles:
    - haproxy

- name: deploy tomcat
  hosts: apps
  gather_facts: false
  tags:
    - tomcat
  roles:
    - tomcat